app/models/article.py
from datetime import datetime

from . import db, DataBaseMixin


class Article(db.Model, DataBaseMixin):
    __tablename__ = 'article'

    id = db.Column(db.Integer, db.Sequence('article_id_seq'), primary_key=True)
    title = db.Column(db.Unicode, nullable=False)
    title_type = db.Column(db.UnicodeText(32))
    abstract = db.Column(db.Unicode)
    abstract_type = db.Column(db.UnicodeText(32))
    text = db.Column(db.Unicode)
    text_type = db.Column(db.UnicodeText(32))
    visible = db.Column(db.Boolean)
    accessible = db.Column(db.Boolean)
    create_at = db.Column(db.DateTime(timezone=True))

    @classmethod
    def create(cls, title, title_type='HTML', abstract='', abstract_type='HTML', text='', text_type='HTML',
               visible=True, accessible=True, create_at=None):
        obj = cls(title=title,
                  title_type=title_type,
                  abstract=abstract,
                  abstract_type=abstract_type,
                  text=text,
                  text_type=text_type,
                  visible=visible,
                  accessible=accessible,
                  create_at=create_at or datetime.now())
        obj.save()

    @classmethod
    def get_by_id(cls, aid):
        return cls.query.get(aid)

    @classmethod
    def get_all(cls):
        return cls.query.all()

app/article/__init__.py
from flask import request, jsonify

from app import user_logined
from app.models.article import Article
from app.utils import Blueprint

blueprint = Blueprint('article', __name__)


@blueprint.route('/')
def index():
    context = {
        'article_list': Article.query.all()
    }
    return blueprint.render_template('index.html', **context)


@blueprint.route('/articles')
def all_articles():
    return Article.get_all()


@blueprint.route('/articles/<string:aid>', endpoint='article', methods=['GET', 'POST', 'DELETE'])
def article(aid):
    context = {
        'article': Article.query.get(aid)
    }
    if request.method == 'GET':
        if request.args.get('api'):
            if context['article']:
                return jsonify({
                    'title': context['article'].title,
                    'abstract': context['article'].abstract,
                    'text': context['article'].text
                })
            else:
                return ({'message': '获取失败'}), 503
        else:
            return blueprint.render_template('article.html', **context)

    if request.method == 'DELETE':
        if context['article']:
            # 没登陆，则假删
            if user_logined():
                context['article'].delete()
            return '', 204
        else:
            return jsonify({'message:' '删除失败'}), 503

myblog/app/views/main.py
from models.articles import Articles
from flask import render_template, request, jsonify
from flask.blueprints import Blueprint

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
def index():
    #print(request.user_logined)
    context = {
        'article_list': Articles.query.all()
    }
    return render_template('main/index.html', **context)


@blueprint.route('/articles/<int:article_id>')
def article(article_id):
    context = {
        'article': Articles.query.get(article_id)
    }
    return render_template('main/article.html', **context)


@blueprint.route('/websocket')
def websocket():
    return render_template('main/websocket.html')

app/templates/main/article.html
{% extends 'base/default.html' %}

{% block styles %}

<style>
    {% if has_plugin %}
    {% endbif %}
</style>

{% endblock %}


{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="mt-5" style="max-width: 650px;">
            <div id="article">
                {% if article %}
                    <div class="mb-3 border-bottom">
                        {{ article.title | safe }}
                    </div>
                    {% if article.text %}
                        {{ article.text| safe_without_code }}
                    {% else %}
                        <div style="line-height: 1.2;">
                            <p>The blog content is empty.<br>
                                这篇博客的内容是空的。</p>
                        </div>
                    {% endif %}
                    <div class="text-center mt-3">
                        <p class="small" style="color: #c8c8c8;">{{ article.create_at }} 发布</p>
                    </div>
                {% else %}
                    <div>不存在的博客</div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        (function () {
            let article = document.getElementById('article');
            for (let code of article.getElementsByTagName('code')) {
                // 去掉前后空白字符
                let raw_html = code.innerHTML;
                code.innerText = raw_html.trim();
            }
        }());
        {% if has_plugin %}
            // 采用动态加载插件，是为了防止网络蜘蛛爬取到侵权的内容
            (function () {
                // plugins loading
                {% render_javascript() %}
            }());
        {% endif %}
    </script>
{% endblock %}

app/templates/main/index.html
{% extends 'base/default.html' %}


{% block header %}
    <nav class="navbar navbar-light bg-light">
        <div>
            <a class="navbar-brand mb-0 h2" style="line-height: 1.1;" href="/">浮砂的博客</a>
            <small><a href="{{ url_for('admin.index') }}">后台</a></small>
        </div>
    </nav>
    <a href="https://github.com/fushall/myblog"><img style="position: fixed; top: 0; right: 0; border: 0;"
                                                     src="http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"
                                                     alt="Fork me on GitHub"></a>
{% endblock %}


{% block styles %}
    <style>
        .link {
            color: #1d2124;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="mt-4">
            <ul>
                {% for article in article_list %}
                    <li>
                        <div>
                            <a class="link"
                               href="{{ url_for('main.article', article_id=article.id) }}">{{ article.title| safe }}</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}